#!/bin/sh
read -p "Loaded Dvcky QAI1 \(Quick Arch Install\)!"
timedatectl set-ntp true
fdisk -l
read -p "Enter drive to install arch here: " drive
fdisk $drive
fdisk -l $drive
read -p "Enter boot partition: " boot
read -p "Enter linux partition: " linux
mkfs.fat -F32 $boot
mkfs.ext4 $linux
mount $linux /mnt
pacstrap /mnt base base-devel linux linux-firmware nano
genfstab -U /mnt >> /mnt/etc/fstab
echo Done! Run \"arch-chroot /mnt\", then download and run part 2.
rm 1
