#!/bin/sh
read -p "Loaded Dvcky QAI2 \(Quick Arch Install\)!"
find /usr/share/zoneinfo -printf "%P\n"
read -p "Enter timezone (format: Zone/SubZone): " time
ln -sf /usr/share/zoneinfo/$time /etc/localtime
hwclock --systohc
nano /etc/locale.gen
locale-gen
echo "LANG=" >> /etc/locale.conf
read -p "Retype language chosen after pressing enter..."
nano /etc/locale.conf
read -p "Choose system name: " name
echo "$name" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 $name.localdomain $name" >> /etc/hosts
mkinitcpio -P
passwd
pacman -S celluloid curl efibootmgr evince file-roller gdm gedit git gnome-control-center gnome-shell gnome-system-monitor gnome-terminal gnome-tweaks grub gthumb nautilus networkmanager networkmanager-openvpn noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra nvidia nvidia-settings pacman-contrib pulseaudio sudo xdg-user-dirs
mkdir /boot/efi
read -p "Enter boot partition: " boot
mount $boot /boot/efi
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
read -p "Add \"nvidia-drm.modeset=1\" in \"GRUB_CMDLINE_LINUX_DEFAULT\"."
nano /etc/default/grub
read -p "Now, add \"nvidia nvidia_modeset nvidia_uvm nvidia_drm\" in \"MODULES\"."
nano /etc/mkinitcpio.conf
mkinitcpio -P
grub-mkconfig -o /boot/grub/grub.cfg
nano /etc/pacman.conf
read -p "Enter username: " uname
useradd -m -G wheel $uname
passwd $uname
read -p "Uncomment \"%wheel ALL=\(ALL\) ALL\" to give users sudo permission."
EDITOR=nano visudo
systemctl enable gdm
systemctl enable NetworkManager
systemctl enable bluetooth
echo Done! Type \"exit\", then \"reboot now\".
rm 2
